package com.tvo.technologies.saferecruitment.model.enums;

public enum RedFlags {
    UNREALISTIC_SALARY,
    VAGUE_JOB_DESCRIPTION,
    RUSHED_PROCESS_NO_INTERVIEW,
    MISMATCHED_SKILLS_AND_PAY,
    LANGUAGE_INDICATING_FEES,
    HIGH_RISK_REMOTE_LOCATION,
    VAGUE_BUSINESS_MODEL,
    INCONSISTENT_ADDRESS_TYPE,
    NO_PHYSICAL_PRESENCE,
    ILLEGAL_ACTIVITY_SUGGESTIONS,
    INCONSISTENT_DATA,
    WEBSITE_LOW_QUALITY_OR_NEW,
    GENERIC_REVIEWS_PRAISE,
    MANY_NEGATIVE_REVIEWS,
    NO_RED_FLAGS
}
